<a href="https://colab.research.google.com/github/Queila-Cruz/Projeto_Case_Efeito_Fancy/blob/main/07_08_desafio_fancy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

!git clone https://github.com/ChiaviniK/fancygeneration

Cloning into 'fancygeneration'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (14/14), 560.96 KiB | 2.76 MiB/s, done.
Resolving deltas: 100% (4/4), done.

In [2]:
clientes = '/content/fancygeneration/perfil_clientes.csv'
vendas = '/content/fancygeneration/vendas_pedidos.csv'
produtos = '/content/fancygeneration/catalogo_produtos.csv'

df_clientes = pd.read_csv(clientes)
df_vendas = pd.read_csv(vendas)
df_produtos = pd.read_csv(produtos)

In [3]:
#Junção das Tabelas

#Vendas + Produtos
df_produtos_vendas = pd.merge(
    df_vendas,
    df_produtos,
    left_on='sku_produto',
    right_on='sku_produto',
    how='inner')

#Vendas_Produtos + clientes
df_geral = pd.merge(
    df_clientes,
    df_produtos_vendas,
    left_on='id_cliente',
    right_on='id_cliente',
    how='inner'
)
display(df_produtos_vendas)

,id_pedido,id_cliente,sku_produto,data_compra,quantidade,categoria,linha,custo_producao,preco_venda
0,PED000001,CLI03313,SKU037,2025-04-03,2,Vinho,Fancy,22.55,50.24
1,PED000002,CLI05196,SKU046,2025-07-16,2,Café,Fancy,28.93,92.47
2,PED000003,CLI07273,SKU043,2025-03-06,3,Chocolate,Padrão,12.30,17.05
3,PED000004,CLI08699,SKU016,2025-10-26,2,Vinho,Fancy,44.92,112.37
4,PED000005,CLI03599,SKU002,2025-11-23,5,Vinho,Padrão,13.96,19.13
...,...,...,...,...,...,...,...,...,...
49995,PED049996,CLI00565,SKU007,2025-11-15,3,Chocolate,Padrão,10.68,13.22
49996,PED049997,CLI07975,SKU040,2025-12-22,3,Chocolate,Padrão,12.65,17.56
49997,PED049998,CLI09087,SKU027,2025-01-14,4,Queijo,Padrão,16.11,20.55
49998,PED049999,CLI05646,SKU023,2025-08-09,2,Vinho,Padrão,18.37,23.98
49999,PED050000,CLI07325,SKU042,2025-05-18,5,Café,Padrão,22.14,29.93

In [15]:
#Junção das Tabelas + Calculo de Lucros

#Vendas + Produtos
df_produtos_vendas = pd.merge(
    df_vendas,
    df_produtos,
    left_on='sku_produto',
    right_on='sku_produto',
    how='inner')

#Vendas_Produtos + clientes
df_geral = pd.merge(
    df_clientes,
    df_produtos_vendas,
    left_on='id_cliente',
    right_on='id_cliente',
    how='inner'
)

df_geral['Lucro'] = (
    df_geral['preco_venda'] - df_geral['custo_producao']

)


display (df_geral)

,id_cliente,idade,renda_mensal,estado,canal_aquisicao,id_pedido,sku_produto,data_compra,quantidade,categoria,linha,custo_producao,preco_venda,Lucro
0,CLI00001,56,13074.95,BA,Google,PED015566,SKU026,2025-12-05,2,Vinho,Padrão,17.76,22.58,4.82
1,CLI00001,56,13074.95,BA,Google,PED017851,SKU048,2025-05-15,1,Chocolate,Fancy,32.15,97.58,65.43
2,CLI00001,56,13074.95,BA,Google,PED017854,SKU018,2025-11-19,2,Café,Padrão,5.90,7.71,1.81
3,CLI00001,56,13074.95,BA,Google,PED037120,SKU018,2025-05-30,5,Café,Padrão,5.90,7.71,1.81
4,CLI00003,46,6774.69,SP,Orgânico,PED034467,SKU009,2025-03-11,2,Queijo,Padrão,11.40,14.19,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,CLI10000,32,10878.67,SC,Google,PED016413,SKU042,2025-08-31,3,Café,Padrão,22.14,29.93,7.79
49996,CLI10000,32,10878.67,SC,Google,PED033212,SKU031,2025-12-08,5,Queijo,Padrão,14.02,17.80,3.78
49997,CLI10000,32,10878.67,SC,Google,PED038768,SKU019,2025-05-10,4,Queijo,Padrão,6.62,8.72,2.10
49998,CLI10000,32,10878.67,SC,Google,PED042182,SKU021,2025-11-07,2,Queijo,Fancy,34.11,92.27,58.16
49999,CLI10000,32,10878.67,SC,Google,PED048008,SKU012,2025-02-12,2,Café,Padrão,21.24,29.10,7.86

In [18]:
# Calcular o total de itens que tem na coluna quantidade e quantos há na coluna preço de venda
# realiza a soma de cada coluna mencionada
quantidade_total = df_geral['quantidade'].sum()
total_faturamento = df_geral['preco_venda'].sum()

# Realiza o ticket médio de todas as vendas independente do produto

ticket_medio_vendas = total_faturamento / quantidade_total

print (f'O total de itens é de {quantidade_total}')
print(f' O faturamento total é de R$ {total_faturamento:.2f}') # o 2f formata a quantidade de números decimais - os números depois da vírgula,
print(f' O ticket médio é de R$ {ticket_medio_vendas:.2f}')

O total de itens é de 139528
 O faturamento total é de R$ 2224754.70
 O ticket médio é de R$ 15.94

In [19]:
# Calculo para saber quantos clientes únicos tivemos

total_clientes_unicos = df_geral['id_cliente'].nunique() # a função serve para contar o número de elementos únicos (distintos) em uma coluna ou dataframe.
print(f' o total de clientes unicos é de {total_clientes_unicos}')

 o total de clientes unicos é de 9929

In [21]:
# Vamos saber o ticket médio por cliente.
ticket_medio_cliente = total_faturamento / total_clientes_unicos
print(f' O ticket médio por cliente é de R$ {ticket_medio_cliente:.2f}')

 O ticket médio por cliente é de R$ 224.07

In [24]:
# Para efetuar o download da planilh atualizada

df_geral.to_csv('Dados atualizados.csv',index = False) # index false f - você está dizendo ao Pandas para não salvar o índice das linhas no arquivo CSV final.